"""
databricks_jobs — OPTIONAL output for Databricks (Azure or AWS): one notebook-style PySpark job per compiled model plus a Jobs
API 2.1 job spec, rendered from the same compiled dbt models as the Glue output (Azure plan A3; dbt stays the default).
Shares `glue_pyspark.render_job` for the Jinja → Spark SQL resolution; differs in catalog naming (Unity three-part
`catalog.schema.table`), the write (`saveAsTable` Delta by default; MERGE INTO for incremental models) and the job wrapper
(Databricks job with a notebook task, serverless or a named cluster, base parameters for dbt vars).
"""
from __future__ import annotations
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from .glue_pyspark import render_job
from .provenance import NOTEBOOK_MARKER, Provenance

_NB = '''# COMMAND ----------
# MAGIC %md
# MAGIC Model **{model}** - generated by informatica_converter (optional Databricks output; dbt is the default).
# MAGIC Reads Unity Catalog tables, writes `{catalog}.{schema}.{model}`. Widgets: {args}

# COMMAND ----------
import json
CATALOG, SCHEMA, MODEL = "{catalog}", "{schema}", "{model}"
MATERIALIZATION = "{materialization}"
UNIQUE_KEY = {unique_key}
SQL = json.loads(r\'\'\'{sql_json}\'\'\')
for a in {arg_names}:
    dbutils.widgets.text(a, "")
    SQL = {{k: v.replace("${{" + a + "}}", dbutils.widgets.get(a)) for k, v in SQL.items()}}

# COMMAND ----------
target = f"{{CATALOG}}.{{SCHEMA}}.{{MODEL}}"
exists = spark.catalog.tableExists(target)
branch = "incremental" if (exists and "incremental" in SQL) else "full"
df = spark.sql(SQL[branch])
if MATERIALIZATION == "incremental" and exists and UNIQUE_KEY:
    df.createOrReplaceTempView("_src")
    on = " AND ".join(f"t.{{k}} = s.{{k}}" for k in UNIQUE_KEY)
    spark.sql(f"MERGE INTO {{target}} t USING _src s ON {{on}} WHEN MATCHED THEN UPDATE SET * WHEN NOT MATCHED THEN INSERT *")
else:
    df.write.mode("overwrite").option("overwriteSchema", "true").saveAsTable(target)
print(f"{{MODEL}}: {{branch}} -> {{target}}")
'''


def write_databricks_jobs(outs: List[Any], out_dir: Path, *, catalog: str, schema: str, source_map: Optional[Dict[str, str]] = None,
                          rendered_at: str, source_hash: str, folder: str, notebook_root: str = "/Workspace/Shared/datapai/informatica") -> Dict[str, Any]:
    """Write databricks_jobs/<model>.py notebooks and jobs.json (Jobs API 2.1 specs). source_map: dbt source name → 'catalog.schema'."""
    jdir = Path(out_dir) / "databricks_jobs"; jdir.mkdir(parents=True, exist_ok=True)
    jobs: List[Dict[str, Any]] = []; failed: List[Dict[str, str]] = []
    src_dbs = {k: v for k, v in (source_map or {}).items()}
    for o in outs:
        if getattr(o, "decision", "") == "skip" or not getattr(o, "sql", ""):
            continue
        try:
            sql_json, args = render_job(o.name, o.sql, target_db=f"{catalog}.{schema}", source_dbs=src_dbs or None, materialization=o.materialization, unique_key=o.unique_key)
        except Exception as exc:  # noqa: BLE001
            failed.append({"model": o.name, "error": f"{type(exc).__name__}: {str(exc)[:160]}"}); continue
        body = _NB.format(model=o.name, catalog=catalog, schema=schema, args=", ".join(args) or "none", materialization=o.materialization,
                          unique_key=json.dumps(o.unique_key), sql_json=sql_json, arg_names=json.dumps(args))
        rendered = Provenance(source_hash=source_hash, object=f"{folder}/{o.mapping}/{o.target}", template_id="informatica.databricks_notebook",
                              rendered_at=rendered_at).render(body, ".py")
        # marker first; the provenance header forms the first (comment-only) cell; the markdown cell starts after COMMAND ----------
        (jdir / f"{o.name}.py").write_text(NOTEBOOK_MARKER + "\n" + rendered, encoding="utf-8")
        jobs.append({"name": f"infa_{o.name}", "tasks": [{"task_key": o.name, "notebook_task": {"notebook_path": f"{notebook_root}/{o.name}", "base_parameters": {a: "" for a in args}},
                                                          "environment_key": "default"}],
                     "environments": [{"environment_key": "default", "spec": {"client": "2"}}],   # serverless; replace with job_cluster for a named cluster
                     "tags": {"datapai:component": "informatica_converter", "model": o.name}, "max_concurrent_runs": 1})
    (jdir / "jobs.json").write_text(json.dumps({"catalog": catalog, "schema": schema, "jobs": jobs, "failed": failed}, indent=1), encoding="utf-8")
    return {"jobs": len(jobs), "failed": failed}
