"""
project — write the dbt project the compiler produced: one model per PowerCenter target, `_sources.yml` per folder (one dbt
source per DBD / lookup connection, tables typed from the export), `_models.yml` (descriptions, not-null on primary keys,
unique on single-column keys), `dbt_project.yml` with the estate's Iceberg conventions, and a `CONVERSION.md` that lists
every TODO the compiler raised. Adapter-neutral on purpose: the project builds on whichever profile you point it at; dbt's
adapter renders the portable SQL and the cross-database macros.

    write_project(folders, out_dir, project_name="infa_sales_dw", profile="infa_sales_dw") → summary dict
"""
from __future__ import annotations
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Dict, List, Optional

from .compiler import ModelOut, _id, compile_mapping
from .model import Folder

_TYPE = {"number": "numeric", "decimal": "numeric", "bigint": "bigint", "integer": "integer", "int": "integer", "smallint": "integer",
         "double": "float", "float": "float", "real": "float", "varchar2": "string", "varchar": "string", "nvarchar2": "string",
         "nvarchar": "string", "char": "string", "nchar": "string", "string": "string", "text": "string", "clob": "string",
         "date": "timestamp", "date/time": "timestamp", "datetime": "timestamp", "timestamp": "timestamp", "raw": "binary"}


def _yml_type(dt: str) -> str:
    return _TYPE.get(re.sub(r"\(.*\)", "", (dt or "").strip().lower()), "string")


def _yaml_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def convert_folder(folder: Folder) -> List[ModelOut]:
    outs: List[ModelOut] = []
    for m in folder.mappings:
        outs.extend(compile_mapping(m, folder))
    return outs


def write_project(folders: List[Folder], out_dir: Path, project_name: str = "informatica_conversion", profile: Optional[str] = None,
                  materialized_default: str = "table", iceberg: bool = True) -> Dict[str, Any]:
    out_dir = Path(out_dir); models_root = out_dir / "models"
    summary: Dict[str, Any] = {"project": project_name, "folders": [], "models": 0, "skipped": 0, "todos": 0}
    for f in folders:
        fdir = models_root / _id(f.name); fdir.mkdir(parents=True, exist_ok=True)
        outs = convert_folder(f)
        # several mappings loading the same target → model per (mapping, target), with a note; one mapping → model per target
        by_target = Counter(o.target for o in outs)
        for o in outs:
            if by_target[o.target] > 1:
                o.name = f"{_id(o.mapping)}__{_id(o.target)}"
                o.todos = sorted(set(o.todos) | {f"target {o.target} is loaded by {by_target[o.target]} mappings — union or sequence them (one model per mapping generated)"})
        src_tables: Dict[str, Dict[str, Dict[str, Any]]] = defaultdict(dict)     # source_name → table → {identifier, columns}
        sdefs = {s.name: s for s in f.sources}
        model_yml: List[str] = ["version: 2", "", "models:"]
        conv_md: List[str] = [f"# Conversion notes · folder {f.name}", ""]
        n_todo = 0
        for o in outs:
            for s in o.sources:
                sd = sdefs.get(s["identifier"])
                src_tables[s["source_name"]][s["table"]] = {"identifier": s["identifier"], "dbd": s["dbd"],
                                                            "columns": [(p.name, p.datatype, p.keytype) for p in (sd.fields if sd else [])]}
            if o.decision == "skip":
                summary["skipped"] += 1
                (fdir / f"{o.name}.sql.skipped").write_text("-- NOT CONVERTED (needs review)\n" + "\n".join(f"-- {t}" for t in o.todos) + "\n", encoding="utf-8")
                conv_md += [f"## {o.name} — SKIPPED", ""] + [f"- {t}" for t in o.todos] + [""]
                continue
            header = [f"-- {o.name}: converted from PowerCenter target {o.target} (mapping decision: {o.decision})",
                      "-- Generated by informatica_converter; review every TODO below before enabling."]
            if o.todos: header += ["-- TODO:"] + [f"--   - {t}" for t in o.todos]
            (fdir / f"{o.name}.sql").write_text("\n".join(header) + "\n" + o.sql, encoding="utf-8")
            summary["models"] += 1; n_todo += len(o.todos)
            model_yml += [f"  - name: {o.name}", f"    description: {_yaml_str('Converted from PowerCenter target ' + o.target + '. Decision: ' + o.decision + '.')}"]
            if o.columns:
                model_yml.append("    columns:")
                single_pk = [c for c in o.columns if c["keytype"].upper() == "PRIMARY KEY"]
                for c in o.columns:
                    tests = []
                    if c["keytype"].upper() == "PRIMARY KEY": tests.append("not_null")
                    if len(single_pk) == 1 and c is single_pk[0]: tests.append("unique")
                    line = f"      - name: {c['name']}"
                    if c["datatype"]: line += f"\n        data_type: {_yml_type(c['datatype'])}"
                    if tests: line += "\n        tests: [" + ", ".join(tests) + "]"
                    model_yml.append(line)
            if o.todos: conv_md += [f"## {o.name}", ""] + [f"- {t}" for t in o.todos] + [""]
        # sources
        sy: List[str] = ["version: 2", "", "sources:"]
        for sname, tables in sorted(src_tables.items()):
            sy += [f"  - name: {sname}", f"    description: {_yaml_str('PowerCenter source system (DBD) ' + (next(iter(tables.values()))['dbd'] or sname))}",
                   "    schema: \"{{ var('" + sname + "_schema', '" + sname + "') }}\"", "    tables:"]
            for tname, t in sorted(tables.items()):
                sy += [f"      - name: {tname}", f"        identifier: \"{{{{ var('{sname}_{tname}_identifier', '{t['identifier'].lower()}') }}}}\""]
                if t["columns"]:
                    sy.append("        columns:")
                    for (cn, dt, kt) in t["columns"]:
                        sy.append(f"          - name: {_id(cn)}" + (f"\n            data_type: {_yml_type(dt)}" if dt else ""))
        (fdir / "_sources.yml").write_text("\n".join(sy) + "\n", encoding="utf-8")
        (fdir / "_models.yml").write_text("\n".join(model_yml) + "\n", encoding="utf-8")
        (fdir / "CONVERSION.md").write_text("\n".join(conv_md) + "\n", encoding="utf-8")
        summary["folders"].append({"folder": f.name, "models": len([o for o in outs if o.decision != "skip"]), "skipped": len([o for o in outs if o.decision == "skip"]), "todos": n_todo})
        summary["todos"] += n_todo
    prof = profile or project_name
    ice = "\n      +table_type: iceberg\n      +format: parquet" if iceberg else ""
    (out_dir / "dbt_project.yml").write_text(f"""# Generated by informatica_converter — Informatica PowerCenter → dbt. One model per PowerCenter target; sources per DBD.
# Adapter-neutral: point `profile` at Athena / Snowflake / Databricks / ClickHouse / DuckDB and dbt renders the portable SQL.
name: {project_name}
version: "0.1.0"
config-version: 2
profile: {prof}
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]
require-dbt-version: [">=1.7.0", "<2.0.0"]

vars:
  LOAD_FROM: "1900-01-01"          # PowerCenter mapping parameters ($$X) become dbt vars; set them per environment

models:
  {project_name}:
    +materialized: {materialized_default}
    +tags: ["informatica_conversion", "role_consumer"]{ice}
""", encoding="utf-8")
    (out_dir / "README.md").write_text(f"# {project_name}\n\nGenerated from Informatica PowerCenter exports by `informatica_converter`.\n"
                                       f"Models: {summary['models']} · skipped: {summary['skipped']} · TODOs: {summary['todos']} (see models/*/CONVERSION.md).\n\n"
                                       "    dbt deps && dbt build\n", encoding="utf-8")
    return summary
